### ISSUE TITLE
Provide a release that depends on Pitest 1.1.10

### ISSUE THREAD

**Issue by vmassol** [VinodAnandan/sonar-pitest#13]
Seems that the latest release of this project depends on an oldish version of pitest. Would be nice to have a release that depends on the latest version, which is currently 1.1.10

Thanks for a nice project!

**Comment by bradflood** [comment]
FYI I am working on a PR for pitest 1.2.2 and SonarQube 6.4. https://github.com/bradflood/sonar-pitest. Feedback welcome

**Comment by VinodAnandan** [comment]
#14
