### ISSUE TITLE
kotlin files not visible on sonar

### ISSUE THREAD

**Issue by sbuisson** [VinodAnandan/sonar-pitest#16]
I've a project with a mix of kotlin and  java file, only the java files are displayed on the Mutation analysis Measures page.

Just for info: both my java and kotlin file are present in the pitest report:
`<mutation detected='false' status='NO_COVERAGE'><sourceFile>Main.java</sourceFile><mutatedClass>some.Main</mutatedClass><mutatedMethod>main</mutatedMethod><methodDescription>([Ljava/lang/String;)V</methodDescription><lineNumber>10</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator><index>5</index><killingTest/><description>removed call to java/io/PrintStream::println</description></mutation>
<mutation detected='false' status='SURVIVED'><sourceFile>MainKotlin.kt</sourceFile><mutatedClass>some.Hello</mutatedClass><mutatedMethod>hello</mutatedMethod><methodDescription>()V</methodDescription><lineNumber>6</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator><index>7</index><killingTest/><description>removed call to java/io/PrintStream::print</description></mutation>
`

**Comment by sarahBuisson** [comment]
I do a pull request to correct this issue: https://github.com/VinodAnandan/sonar-pitest/pull/17

**Comment by VinodAnandan** [comment]
#17 Fixed

**Comment by bradflood** [comment]
@sarahBuisson I'm afraid the test coverage over new code has dropped, and in reviewing further, we don't have any unit tests with kotlin mutations in the mutations.xml file. 

I looked over at the pitest project and couldn't find any examples there either. Would you be able to provide a mutations.xml file generated from pitest generating mutations on kotlin source?

**Comment by sbuisson** [comment]
I don't understand. Do you want I add test to my PR , or do you just want a mutation.xml?

`<?xml version="1.0" encoding="UTF-8"?>
<mutations>
<mutation detected='false' status='NO_COVERAGE'><sourceFile>Main.java</sourceFile><mutatedClass>some.Main</mutatedClass><mutatedMethod>main</mutatedMethod><methodDescription>([Ljava/lang/String;)V</methodDescription><lineNumber>12</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.ConditionalsBoundaryMutator</mutator><index>14</index><killingTest/><description>changed conditional boundary</description></mutation>
<mutation detected='false' status='NO_COVERAGE'><sourceFile>Main.java</sourceFile><mutatedClass>some.Main</mutatedClass><mutatedMethod>main</mutatedMethod><methodDescription>([Ljava/lang/String;)V</methodDescription><lineNumber>13</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.IncrementsMutator</mutator><index>17</index><killingTest/><description>Changed increment from 1 to -1</description></mutation>
<mutation detected='false' status='NO_COVERAGE'><sourceFile>Main.java</sourceFile><mutatedClass>some.Main</mutatedClass><mutatedMethod>main</mutatedMethod><methodDescription>([Ljava/lang/String;)V</methodDescription><lineNumber>12</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator</mutator><index>14</index><killingTest/><description>negated conditional</description></mutation>
<mutation detected='false' status='NO_COVERAGE'><sourceFile>Main.java</sourceFile><mutatedClass>some.Main</mutatedClass><mutatedMethod>main</mutatedMethod><methodDescription>([Ljava/lang/String;)V</methodDescription><lineNumber>10</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator><index>5</index><killingTest/><description>removed call to java/io/PrintStream::println</description></mutation>
<mutation detected='false' status='NO_COVERAGE'><sourceFile>MainKotlin.kt</sourceFile><mutatedClass>some.Workd</mutatedClass><mutatedMethod>world</mutatedMethod><methodDescription>()V</methodDescription><lineNumber>17</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator><index>7</index><killingTest/><description>removed call to java/io/PrintStream::print</description></mutation>
<mutation detected='false' status='SURVIVED'><sourceFile>MainKotlin.kt</sourceFile><mutatedClass>some.World</mutatedClass><mutatedMethod>world</mutatedMethod><methodDescription>()V</methodDescription><lineNumber>17</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator><index>7</index><killingTest/><description>removed call to java/io/PrintStream::print</description></mutation>
<mutation detected='false' status='SURVIVED'><sourceFile>MainKotlin.kt</sourceFile><mutatedClass>some.Hello</mutatedClass><mutatedMethod>hello</mutatedMethod><methodDescription>()V</methodDescription><lineNumber>6</lineNumber><mutator>org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator</mutator><index>7</index><killingTest/><description>removed call to java/io/PrintStream::print</description></mutation>
</mutations>
`

**Comment by bradflood** [comment]
@sbuisson sorry I wasn't very clear. 
What you provided is perfect - I'm not familiar with Kotlin and wanted to understand how pitest reported on Kotlin mutations, specifically the mutatedClass and the sourceFile elements. It appears there is no correlation.   I'm getting ready to refactor to create SQ issues and need to create some Kotlin tests before I start.

**Comment by bradflood** [comment]
@sbuisson the just-completed 0.9-SNAPSHOT build has what I believe is first-class support for mutations in Kotlin code. Could you please evaluate and give feedback on whether Kotlin files show mutation info? They will show as Issues with tags "test-quality" and "test-coverage"
