### ISSUE TITLE
No code coverage displayed on sonar

### ISSUE THREAD

**Issue by sbuisson** [VinodAnandan/sonar-pitest#18]
The mutations found  arent display on the lines of the files

**Comment by bradflood** [comment]
I plan to start work on this soon.

**Comment by bradflood** [comment]
@sbuisson I don't envision the pitest html report being displayed as-is within sonarqube.  The value of sonarqube is that the individual mutations can be translated into SQ issues, and then we can see the "test quality" information in the context of everything else that SQ is reporting on. I would think we could create a pitest-only report using SQ if we wanted to, after the pitest info has been processed in SQ

**Comment by bradflood** [comment]
@sbuisson I think I found a way to create something similar to the default html report you indicate. Before I do that, could you review 0.9-SNAPSHOT, which creates Issues with tags "test-quality" and "test-coverage" and let me know if that provides good enough capabilities?
