### ISSUE TITLE
Rule are inactive by default

### ISSUE THREAD

**Issue by laurentlr** [VinodAnandan/sonar-pitest#27]
In the commit [1ea7d7b7059a5f9b1098c4468366c2328462ca27 ](https://github.com/VinodAnandan/sonar-pitest/commit/1ea7d7b7059a5f9b1098c4468366c2328462ca27) you set the 2 rules inactive by default, but in the **readMe**, you still indicate that "Both rules are active by default"

**Comment by laurentlr** [comment]
@bradflood anyone here ? I can do a PR if you want, but this readMe error made me lose a bit of time.

**Comment by bradflood** [comment]
@laurentlr yes a PR would be appreciated

**Comment by bradflood** [comment]
@laurentlr I've updated the README.md file to correctly indicate that the rules are inactive by default
