### ISSUE TITLE
Plugin for Sonar 4.5.4

### ISSUE THREAD

**Issue by tylersmith34** [VinodAnandan/sonar-pitest#5]
Hi, would it be possible to get this plugin updated for Sonar 4.5.4?  I want to run Pitest using the maven plugin and then import that report with this plugin into our project's Sonar project.

**Comment by mkasprzyk** [comment]
The same question from my side. Support for 4.5.4 would be great :)

**Comment by alexvictoor** [comment]
Hello
I have updated the doc. Indeed you can (an should) use version 0.4 , it works with sonarqube 4.5.4
I have messed up with version 0.5 which only works with sonar 3.7 . sonar plugin api evolution can be tricky :(
Let me know if you encounter any other issue

Alex

**Comment by jchowdhary** [comment]
Hi, i am using version 0.4 and successfully getting my sonar dashboard updated with the pit mutation report.My sonarqube version is 4.5.7. Though the report tell me the %age mutation covered and how many have survived/killed, it does not tell in detail on what lines of code the mutation has survived/killed when we click on the links provided in the PIT report. 
Is there some work is going on for this area..

**Comment by bradflood** [comment]
@jchowdhary - I've updated the plugin for SQ 6 and am willing to consider backward compatibility with SQ 5.  Version 4 is probably too old to support.
