### ISSUE TITLE
No results available in sonar 5.2

### ISSUE THREAD

**Issue by akowpak-miovision** [VinodAnandan/sonar-pitest#7]
Using version 0.6 of the plugin with sonar 5.2, it appears that all of the data is written to sonar, ie:

`14:30:17.292 INFO  - Sensor PitestSensor`
`14:30:17.602 INFO  - Sensor PitestSensor (done) | time=310ms`

However, when I try to look at any mutation data in sonar, it tells me that there is no data available.

**Comment by aleitamar** [comment]
I have the same issue. Did you find a solution or workaround for this?
I am thinking of downgrading to SonarQube 5.1.

**Comment by akowpak-miovision** [comment]
Didn't find a solution or workaround.  Found I had 2 other plugins that no longer worked with 5.2, so I didn't really try.  I'm back on 5.1.2.

If you didn't back up your db before moving to 5.2 downgrading will be easier said than done.

**Comment by gmuecke** [comment]
In SonarQube 5.2 there had been some changes in API and parts of the processing is now done in background on the sonar server. I assembed a fix for this. See PR 
https://github.com/SonarQubeCommunity/sonar-pitest/pull/9

**Comment by anneq** [comment]
We're running on SonarQube 5.2. I can't use the 0.6 plugin as it only supports SonarQube 5.1.X. And all the other versions (forks or otherwise) that I found require SonarQube 5.3. Is my conclusion correct that there is no way of getting pitest to work on SonarQube 5.2?
