### ISSUE TITLE
support for SonarQube 5.3

### ISSUE THREAD

**Issue by bwflood** [VinodAnandan/sonar-pitest#8]
I would like to use this plugin with Sonar 5.3 to take advantage of the "Leak Period". As I understand it, the plugin version 0.6 only works with Sonar 5.1.x.   Thank you for your work on this plugin. Please advise as to when time might become available to release a plugin for sonar 5.3.

**Comment by jdtangney** [comment]
Thanks for this wonderful plugin!

I am now using SonarQube 5.6 LTS and version 0.6 of this plugin. Results don't show up at all in SonarQube so I suspect that some APIs have changed.

Any word on a new release that will work with the LTS Sonar release?

**Comment by thomas-mc-work** [comment]
Try this fork which reportedly works at least with version 5.5:

https://github.com/gmuecke/sonar-pitest

**Comment by jdtangney** [comment]
Thanks! I'll give it a go.

**Comment by timwebster9** [comment]
@jdtangney have you got this to work in 5.6?  I'm having no luck (empty widget).  Other than that it seems to run fine...:-)

**Comment by timwebster9** [comment]
OK, I didn't have the rule enabled.  I enabled it and I can see the issues that have been raised, but the report widget is still empty...

**Comment by timwebster9** [comment]
found the problem - I was building the v0.6 branch because I assumed (wrongly) that the latest release would be the one with the fixes in it.

**Comment by praveendareddy21** [comment]
It might make sense to update this plugin to work with sonarqube 5.6 as it has Long Term Support.

@timwebster9  Are you able to use this plugin with sonarqube 5.6?
If yes, Can you give me instructions on how to do that.
Thank you

**Comment by timwebster9** [comment]
@praveendareddy21 You just clone this [fork](https://github.com/gmuecke/sonar-pitest), build it and install it.  You need to build the master branch (and you'll get a snapshot version).   If you want the rules you need to enable them.  To see the reports, just add the pitest widget.  The readme describes how to run the analysis.

**Comment by bradflood** [comment]
I have updated sonar-pitest to use the SQ 6 APIs, currently verified through 6.6.  Is there interest in backward compatibility with SQ 5 LTS? If so, could you please try 0.9-SNAPSHOT and let me know what problems you see.
